// Run with node --import tsx. Package-local copies let the MCP tarball stand alone.
import { readFileSync, writeFileSync } from 'node:fs';
import { ENDPOINTS } from '../src/endpoints.ts';

const check = process.argv.includes('--check');
const generated = '// Generated by scripts/sync-shared.mjs; edit src/endpoints.ts instead.\n';
const manifest = generated + 'export const ENDPOINT_MANIFEST = ' + JSON.stringify(ENDPOINTS.map(({ path, price, amount, tool }) => ({ path, price, amount, tool })), null, 2) + ' as const;\n';
const read = file => readFileSync(new URL('../' + file, import.meta.url), 'utf8');
const version = JSON.parse(read('mcp/package.json')).version;
const registry = JSON.parse(read('mcp/server.json'));
registry.version = version;
for (const pkg of registry.packages) pkg.version = version;
const outputs = new Map([
  ['src/endpoint-manifest.ts', manifest], ['mcp/endpoint-manifest.ts', manifest],
  ['mcp/payment-policy.ts', read('src/payment-policy.ts')],
  ['mcp/version.ts', '// Generated from mcp/package.json; do not edit.\nexport const MCP_VERSION = ' + JSON.stringify(version) + ';\n'],
  ['mcp/server.json', JSON.stringify(registry, null, 2) + '\n'],
]);
let failed = false;
for (const [file, content] of outputs) {
  let current = ''; try { current = read(file); } catch {}
  if (current.replace(/\r\n/g, '\n') === content.replace(/\r\n/g, '\n')) continue;
  if (check) { console.error(`${file} is out of date; run npm run generate`); failed = true; }
  else writeFileSync(new URL('../' + file, import.meta.url), content);
}
if (failed) process.exitCode = 1;
else console.log(`Shared payment policy, ${ENDPOINTS.length} endpoint prices and MCP version agree.`);
