// Generated by scripts/sync-shared.mjs; edit src/endpoints.ts instead.
export const ENDPOINT_MANIFEST = [
  {
    "path": "/api/price/{symbol}",
    "price": "$0.001",
    "amount": "1000",
    "tool": "get_price"
  },
  {
    "path": "/api/gas",
    "price": "$0.001",
    "amount": "1000",
    "tool": "get_base_gas"
  },
  {
    "path": "/api/trending",
    "price": "$0.002",
    "amount": "2000",
    "tool": "get_trending"
  },
  {
    "path": "/api/base/token/{address}",
    "price": "$0.001",
    "amount": "1000",
    "tool": "get_base_token_price"
  },
  {
    "path": "/api/base/address/{address}",
    "price": "$0.001",
    "amount": "1000",
    "tool": "get_base_address_info"
  },
  {
    "path": "/api/feargreed",
    "price": "$0.001",
    "amount": "1000",
    "tool": "get_fear_greed"
  },
  {
    "path": "/api/base/trending",
    "price": "$0.002",
    "amount": "2000",
    "tool": "get_base_trending_pools"
  },
  {
    "path": "/api/brief",
    "price": "$0.005",
    "amount": "5000",
    "tool": "get_market_brief"
  },
  {
    "path": "/api/base/radar",
    "price": "$0.003",
    "amount": "3000",
    "tool": "get_new_token_radar"
  },
  {
    "path": "/api/try/premium",
    "price": "$0.002",
    "amount": "2000",
    "tool": "get_try_premium"
  },
  {
    "path": "/api/try/spread",
    "price": "$0.002",
    "amount": "2000",
    "tool": "get_try_spread"
  },
  {
    "path": "/api/base/portfolio/{address}",
    "price": "$0.003",
    "amount": "3000",
    "tool": "get_base_portfolio"
  },
  {
    "path": "/api/base/safety/{address}",
    "price": "$0.003",
    "amount": "3000",
    "tool": "check_token_safety"
  },
  {
    "path": "/api/base/scout",
    "price": "$0.008",
    "amount": "8000",
    "tool": "scout_new_tokens"
  },
  {
    "path": "/api/base/fresh",
    "price": "$0.004",
    "amount": "4000",
    "tool": "get_fresh_pools"
  },
  {
    "path": "/api/base/radar/history",
    "price": "$0.002",
    "amount": "2000",
    "tool": "get_radar_history"
  },
  {
    "path": "/api/base/scorecard",
    "price": "$0.005",
    "amount": "5000",
    "tool": "get_radar_scorecard"
  },
  {
    "path": "/api/base/name/{nameOrAddress}",
    "price": "$0.001",
    "amount": "1000",
    "tool": "resolve_basename"
  },
  {
    "path": "/api/watch/address/{address}",
    "price": "$0.002",
    "amount": "2000",
    "tool": "watch_base_address"
  },
  {
    "path": "/api/watch/radar",
    "price": "$0.003",
    "amount": "3000",
    "tool": "watch_new_tokens"
  },
  {
    "path": "/api/watch/price/{symbol}",
    "price": "$0.001",
    "amount": "1000",
    "tool": "watch_price_alert"
  }
] as const;
